Almilosz/js api
vishniakov-nikolai/openvino pull request #1
Opened 2023-04-02 19:14 UTC by almilosz

### Details:
 - Merge changes with js-wasm-proto
 - Refactor of source files
 - Add hello_world javascript jupyter notebook
 - Add methods required to implement ISession, IShape, IModel interfaces

### Tickets:
 - 102916
 - 102902

2023-04-05 13:01 UTC, vishniakov-nikolai requested changes
Please, check files with which have empty last line warning.
I left several minor comments. After them fix it is possible to merge.

2023-04-13 10:30 UTC, almilosz commented on samples/js/assets/images/coco.jpg
I will remove this photo and add a different one that has its original shape and needs resizing.

2023-04-13 10:55 UTC, almilosz commented on samples/js/node-addon/README.md
Done

2023-04-13 10:57 UTC, almilosz commented on samples/js/node-addon/README.md
> +$ node <example-name> <path-to-image> <path-to-model>
I am not sure what you meant, but I changed it and now it is optional to pass image path. We can get back to it later

2023-04-13 11:01 UTC, almilosz commented on samples/js/node-addon/imagenet_2012_labels.txt
It is possible. I was just wondering why is it better to create a .mjs file instead using simple .txt and reading it

2023-04-13 11:04 UTC, almilosz commented on src/bindings/js/node-addon/package.json
> +    "name": "hello",
I renamed it to "openvinojs-node"

2023-04-13 11:07 UTC, almilosz commented on samples/js/node-addon/package.json
> +        "preinstall": "echo ${INTEL_OPENVINO_DIR?\\$INTEL_OPENVINO_DIR should set before installation. Please execute 'source ~/intel/openvino/setupvars.sh' and run 'npm i' again.}"
Path to INTEL_OPENVINO_DIR  is still required. Current node addon binding does not contain C++ binaries.

2023-04-13 11:57 UTC, vishniakov-nikolai commented on samples/js/assets/images/coco.jpg
So cute! 😻

2023-04-17 08:31 UTC, merged